// TODO: Ezeket definiálni
#define LONG_STRIP_SECTION_COUNT 80
#define SHORT_STRIP_SECTION_COUNT 30
#define STRIP_GAP_SECTION_COUNT 11

#define LED_ARRAY_COUNT (LONG_STRIP_SECTION_COUNT + SHORT_STRIP_SECTION_COUNT + STRIP_GAP_SECTION_COUNT)