// TODO: Ezeket definiálni
#define LONG_STRIP_SECTION_COUNT 71
#define SHORT_STRIP_SECTION_COUNT 10
#define STRIP_GAP_SECTION_COUNT 15

#define LED_ARRAY_COUNT (LONG_STRIP_SECTION_COUNT + SHORT_STRIP_SECTION_COUNT + STRIP_GAP_SECTION_COUNT)